<!DOCTYPE html>
<html>
   <head>
      <meta name="viewport" content="width=device-width"/>
      <meta charSet="utf-8"/>
      <title>CrunchyCows</title>
      <meta name="description" content="Generated by create next app"/>
      <link href="img/CC-favicon.png" type="image/png" rel="icon"/>
      <meta name="next-head-count" content="5"/>
      <link rel="preload" href="/_next/static/css/b21fdfae5e63415a1d21.css" as="style"/>
      <link rel="stylesheet" href="/_next/static/css/b21fdfae5e63415a1d21.css" data-n-g=""/>
      <noscript data-n-css=""></noscript>
      <script defer="" nomodule="" src="/_next/static/chunks/polyfills-e7a279300235e161e32a.js"></script><script src="/_next/static/chunks/webpack-6cca8f10f816799d8144.js" defer=""></script><script src="/_next/static/chunks/framework-a184356a51a3a5901408.js" defer=""></script><script src="/_next/static/chunks/main-334d7763bbcde973ab57.js" defer=""></script><script src="/_next/static/chunks/pages/_app-7a31776609cc7e5b1224.js" defer=""></script><script src="/_next/static/chunks/0a6e12db-052c34a7765e036cf1b8.js" defer=""></script><script src="/_next/static/chunks/970-0d631ccf532dae9db7fb.js" defer=""></script><script src="/_next/static/chunks/pages/index-3772a8991451fc411da2.js" defer=""></script><script src="/_next/static/Pr6c9aHeV6D7BUCsyX8zD/_buildManifest.js" defer=""></script><script src="/_next/static/Pr6c9aHeV6D7BUCsyX8zD/_ssgManifest.js" defer=""></script>
   </head>
   <body>
      <div id="__next">
         <div>
            <body>
               <header class="">
                  <div class="container">
                     <div class="row">
                        <div class="col-md-4 col-sm-6 col-8 text-left">
                           <div class="logo"><a href="#"><img src="img/logo.png" alt=""/></a></div>
                        </div>
                        <div class="col-md-8 col-sm-6 col-4 d-flex align-items-center justify-content-end">
                           <div class="mobile-menu d-flex align-items-center">
                              <ul id="menu">
                                 <li class="nav-item"><a href="#collect-head" class="nav-link">Collect Cows</a></li>
                                 <li class="nav-item"><a href="#rare-box" class="nav-link menu_link">Rare</a></li>
                                 <li class="nav-item"><a href="#text-center" class="nav-link menu_link">FAQ</a></li>
                              </ul>
                              <div class="d-inline-flex align-items-center"><a class="wallet-btn" href="#">Wallet</a><a class="nouka-icon" href="https://opensea.io/collection/crunchycows"><img src="img/nouka-icon.png" alt=""/></a></div>
                           </div>
                           <div class="hamburger-menu"><span class="line-top"></span><span class="line-center"></span><span class="line-bottom"></span></div>
                        </div>
                     </div>
                  </div>
               </header>
               <div class="home-wrapper" style="background-image:url(./img/home-bgs.png)">
                  <img class="home-shape-two position-absolute" src="img/home-shape-two.png" alt=""/><img class="home-shape-bg position-absolute" src="img/home-shape-bg.png" alt=""/>
                  <div class="container">
                     <div class="row justify-content-center">
                        <div class="col-lg-12 home-content-ab">
                           <div class="home-content">
                              <div class="d-flex align-items-center">
                                 <img class="home-cow" src="img/home-cow.png" alt=""/>
                                 <div>
                                    <p>Crunchy Cows are a collection of <br/> 9,999 fun loving, food chomping NFT <br/> friends, cruising on the Ethereum <br/> block chain.</p>
                                    <p class="mt_custom">Collect some cows and come on <br/> down to the Cow Club!</p>
                                    <span class="moo-text">-Moo</span>
                                 </div>
                              </div>
                              <div class="d-flex"><a class="twitter-bg-new social-btn-new" href="https://twitter.com/crunchycows"><img src="img/twitter-logo.png" alt=""/>Twitter</a><a class="social-btn-new discord-bg" href="https://discord.gg/w8XejnBx"><img src="img/discord-icon.png" alt=""/>Discord</a><a class="buy-bg social-btn-new" href="#">Buy</a></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="pre-wrapper" style="background-image:url(./img/pre-sale-bg.png)">
                  <div class="container">
                     <div class="row">
                        <div class="col-12">
                           <div class="pre-box text-center">
                              <h2>CRUNCHY COW MOOS (NEWS)</h2>
                              <h4>Be the first to get updates, news, and drop info.</h4>
                              <div class="search-box"><input type="text" placeholder="Enter Your Email"/><button type="button" class="sign-btn">SIGN Me Up</button></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="collect-currency-wrapper" style="background-image:url(./img/collect-currency-bg.png)">
                  <div class="container">
                     <div class="row justify-content-center">
                        <div class="col-12 text-center">
                           <h2 class="collect-head" id="collect-head">Collect Crunchy Cows</h2>
                           <p class="collect-head" id="collect-head">
                              -<!-- -->
                           </p>
                        </div>
                        <div class="col-lg-4 col-md-6 col-sm-6">
                           <div class="collect-box mt_30 text-center">
                              <img class="collect-img" src="img/collect-img-01.png" alt=""/>
                              <h3 class="mt_10">Single Serving</h3>
                              <p class="color-one mt_10">1 Cow</p>
                              <p class="mt_10">
                                 -<!-- --> ETH per Cow
                              </p>
                              <button data-toggle="modal" data-target="#exampleModal" href="-" class="mint-btn mt_30" type="button"> MINT</button>
                           </div>
                        </div>
                        <div class="col-lg-4 col-md-6 col-sm-6">
                           <div class="collect-box mt_30 text-center">
                              <img class="collect-img" src="img/collect-img-02.png" alt=""/>
                              <h3 class="mt_10">Combo</h3>
                              <p class="color-one mt_10">2 Cows</p>
                              <p class="mt_10">
                                 -<!-- --> ETH per Cow
                              </p>
                              <button data-toggle="modal" data-target="#exampleModal" class="mint-btn mt_30" type="button">MINT</button>
                           </div>
                        </div>
                        <div class="col-lg-4 col-md-6 col-sm-6">
                           <div class="collect-box mt_30 text-center">
                              <img class="collect-img" src="img/collect-img-03.png" alt=""/>
                              <h3 class="mt_10">Super Sized</h3>
                              <p class="color-one mt_10">3 Cows</p>
                              <p class="mt_10">
                                 -<!-- --> ETH per Cow
                              </p>
                              <button data-toggle="modal" data-target="#exampleModal" class="mint-btn mt_30" type="button">MINT</button>
                           </div>
                        </div>
                        <div class="col-12 text-center"><a class="opensa-btn" href="https://opensea.io/collection/crunchycows">Opensea</a></div>
                     </div>
                  </div>
               </div>
               <div class="perks-wrapper position-relative">
                  <img class="perk-shape-01 position-absolute" src="img/perk-shape-01.svg" alt=""/><img class="perk-shape-02 position-absolute" src="img/perk-shape-02.svg" alt=""/><img class="perk-shape-03 position-absolute" src="img/perk-shape-03.svg" alt=""/><img class="perk-shape-04 position-absolute" src="img/perk-shape-04.svg" alt=""/><img class="perk-shape-05 position-absolute" src="img/perk-shape-05.svg" alt=""/><img class="perk-shape-06 position-absolute" src="img/perk-shape-06.svg" alt=""/><img class="perk-shape-07 position-absolute" src="img/perk-shape-07.svg" alt=""/><img class="perk-shape-08 position-absolute" src="img/perk-shape-08.svg" alt=""/><img class="perk-shape-09 position-absolute" src="img/perk-shape-09.svg" alt=""/><img class="perk-shape-10 position-absolute" src="img/perk-shape-10.svg" alt=""/><img class="perk-shape-11 position-absolute" src="img/perk-shape-11.svg" alt=""/><img class="perk-shape-12 position-absolute" src="img/perk-shape-12.svg" alt=""/>
                  <div class="container">
                     <div class="row">
                        <div class="col-12">
                           <div>
                              <div class="text-center">
                                 <h2 class="collect-head perks-head">PERKS</h2>
                              </div>
                              <ul class="park-box">
                                 <li>
                                    <img src="img/tick-icon.svg" alt=""/>
                                    <p>Crunchy Cow Country Club Access (2022)</p>
                                 </li>
                                 <li>
                                    <img src="img/tick-icon.svg" alt=""/>
                                    <p>Owners eligible to get air-dropped custom cows</p>
                                 </li>
                                 <li>
                                    <img src="img/tick-icon.svg" alt=""/>
                                    <p>First dibs on pre-sale of Mad/Happy Crunchy Cows and Crunchy Cow Friends in the future</p>
                                 </li>
                                 <li>
                                    <img src="img/tick-icon.svg" alt=""/>
                                    <p>Cow Card</p>
                                 </li>
                                 <li>
                                    <img src="img/tick-icon.svg" alt=""/>
                                    <p>Crunchy Cow Investor &amp; Launch Updates</p>
                                 </li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="rare-wrapper" style="background-image:url(./img/rare-bg.png)">
                  <div class="container">
                     <div class="rare-box">
                        <div class="row">
                           <div class="col-12 text-center">
                              <h2 class="collect-head rare-head" id="rare-box">RARE</h2>
                           </div>
                           <div class="col-lg-6 col-md-6">
                              <div class="text-center">
                                 <div class="toltip-box">
                                    <img class="tolitp-shape position-absolute" src="img/tolitp-shape.png" alt=""/>
                                    <p>Could we use a different<br/> word other than rare?</p>
                                 </div>
                                 <img class="rare-cow-img" src="img/rare-cow-img.png" alt=""/>
                              </div>
                           </div>
                           <div class="col-lg-6 col-md-6">
                              <div class="table-make">
                                 <table>
                                    <tr class="border-bottom-table">
                                       <td>
                                          <p class="table-first-text mb_10">TOTAL COWS</p>
                                       </td>
                                       <td class="text-left">
                                          <h5 class="table-second-text mb_10">9,999</h5>
                                       </td>
                                    </tr>
                                    <tr class="border-bottom-table">
                                       <td>
                                          <p class="table-first-text mt_20 mb_10">Generated</p>
                                       </td>
                                       <td class="text-left">
                                          <h5 class="table-second-text mt_20 mb_10">0</h5>
                                       </td>
                                    </tr>
                                    <tr class="border-bottom-table">
                                       <td>
                                          <p class="table-first-text mt_20 mb_10">Custom (Originals)</p>
                                       </td>
                                       <td class="text-left">
                                          <h5 class="table-second-text mt_20 mb_10">300</h5>
                                       </td>
                                    </tr>
                                    <tr class="border-bottom-table">
                                       <td>
                                          <p class="table-first-text mt_20 mb_10">Super Rare </p>
                                       </td>
                                       <td class="text-left">
                                          <h5 class="table-second-text mt_20 mb_10">2%</h5>
                                       </td>
                                    </tr>
                                    <tr class="border-bottom-table">
                                       <td>
                                          <p class="table-first-text mt_20 mb_10">Rare</p>
                                       </td>
                                       <td class="text-left">
                                          <h5 class="table-second-text mt_20 mb_10">8%</h5>
                                       </td>
                                    </tr>
                                    <tr class="border-bottom-table">
                                       <td>
                                          <p class="table-first-text mt_20 mb_10">Uncommon </p>
                                       </td>
                                       <td class="text-left">
                                          <h5 class="table-second-text mt_20 mb_10">25%</h5>
                                       </td>
                                    </tr>
                                    <tr class="border-bottom-table border-table-last">
                                       <td>
                                          <p class="table-first-text mt_30 mb_10">Common</p>
                                       </td>
                                       <td class="text-left vertical-text">
                                          <h5 class="table-second-text mt_30 mb_10">65%</h5>
                                       </td>
                                    </tr>
                                 </table>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="road-map-wrapper position-relative">
                  <div class="container">
                     <div class="row">
                        <div class="col-12 position-relative text-center">
                           <h2 class="collect-head text-white road-map-head">Road Map</h2>
                           <img class="road-map-img" src="img/road-map-img.png" alt=""/>
                           <div class="road-map-ab">
                              <h3 class="road-percent">10%</h3>
                              <p class="road-map-para road-map-ab-1">10 Airdrops <br/> For Every 1000 <br/> Cows Minted</p>
                           </div>
                           <div class="road-map-ab">
                              <h3 class="road-percent">20%</h3>
                              <p class="road-map-para road-map-ab-2">$5k Donation Made +<br/> Donation Partners<br/> Announced </p>
                           </div>
                           <div class="road-map-ab">
                              <h3 class="road-percent">30%</h3>
                              <p class="road-map-para road-map-ab-3">10 Fresh <br/>Air-Drops to<br/>Random Cow <br/>Owners</p>
                           </div>
                           <div class="road-map-ab">
                              <h3 class="road-percent">50%</h3>
                              <div class="road-map-ab-4">
                                 <p class="road-map-para">Crunchy Cow<br/>Country Club Opens</p>
                              </div>
                           </div>
                           <div class="road-map-ab">
                              <h3 class="road-percent">75%</h3>
                              <div class="road-map-ab-5">
                                 <p class="road-map-para">50 Fresh Airdrops<br/>on Cow Owner&#x27;s Heads</p>
                                 <p class="road-map-para mt_20">Crunchy Cow<br/>Merch and Cartoon <br/>Announcements</p>
                              </div>
                           </div>
                           <div class="road-map-ab">
                              <h3 class="road-percent">100%</h3>
                              <p class="road-map-para road-map-ab-6">Moo-ning Soon!</p>
                           </div>
                        </div>
                        <div class="col-12">
                           <p class="road-map-last-para">Mad Crunchy Cows, Crazy Cow Generator, Crunchy Cow Friends,<br/> And so moo-ch more.</p>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="who-make-wrapper" style="background-image:url(./img/who-make-bg.png)">
                  <div class="container">
                     <div class="row justify-content-center">
                        <div class="col-12 text-center">
                           <h2 class="collect-head who-make-head">WHO Makes These Cows?</h2>
                        </div>
                        <div class="col-lg-3 col-md-4 col-sm-6">
                           <div class="who-make-box mt_30 text-center">
                              <img class="w-100" src="img/who-make-01.png" alt=""/>
                              <h2 class="mt_25">Cow Creator</h2>
                              <p>Ryan Maloney has been creating for a looong time including toys, animated music videos, and picture books. Crunchy Cows is his team&#x27;s 2nd official NFT line. Say hello:   </p>
                              <a class="mt_15" href="https://www.tiktok.com/@ryryart?"><img src="img/tiktok-icon.svg" alt=""/> @ryryart</a>
                           </div>
                        </div>
                        <div class="col-12 text-center">
                           <h2 class="collect-head meet-bros-text text-white">Meet The Moo’s </h2>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="meet-gallery-wrapper">
                  <div class="container-fluid">
                     <div class="popup-gallery row no-gutters custom_grid">
                        <div class="col"><a href="img/gallery-one-01.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-01.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-02.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-02.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-03.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-03.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-04.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-04.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-05.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-05.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-06.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-06.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-07.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-07.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-08.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-08.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-09.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-09.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-10.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-10.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-11.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-11.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-12.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-12.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-13.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-13.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-14.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-14.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-15.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-15.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-16.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-16.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-17.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-17.png" alt=""/></a></div>
                        <div class="col"><a href="img/gallery-one-18.png" class="gallery-img position-relative"><img class="w-100" src="img/gallery-one-18.png" alt=""/></a></div>
                     </div>
                  </div>
               </div>
               <div class="faw-wrapper position-relative" style="background-image:url(./img/faq-bg.png)">
                  <div class="container">
                     <div class="row">
                        <div class="col-12 text-center" id="text-center">
                           <a class="view-btn" href="https://opensea.io/collection/crunchycows">View On Opensea</a>
                           <h2 class="collect-head faq-head">Faq</h2>
                        </div>
                        <div class="col-12">
                           <div class="accordion" id="accordionExample">
                              <div class="card mt_30">
                                 <div class="card-header" id="headingOne">
                                    <h2 class="mb-0" data-toggle="collapse" data-target="#collapseOne" aria-controls="collapseOne">Where can I buy Crunchy Cows?     </h2>
                                 </div>
                                 <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                                    <div class="card-body">Pre-sale: CrunchyCows.com. Public sale: Opensea.io.        </div>
                                 </div>
                              </div>
                              <div class="card mt_40">
                                 <div class="card-header" id="headingtwo">
                                    <h2 class="mb-0" data-toggle="collapse" data-target="#collapsetwo" aria-controls="collapseOne">How do I get Pre-Sale Access?</h2>
                                 </div>
                                 <div id="collapsetwo" class="collapse" aria-labelledby="headingtwo" data-parent="#accordionExample">
                                    <div class="card-body">Sign up for the email list above or join the Discord.</div>
                                 </div>
                              </div>
                              <div class="card mt_40">
                                 <div class="card-header" id="headingthree">
                                    <h2 class="mb-0" data-toggle="collapse" data-target="#collapsethree" aria-expanded="true" aria-controls="collapseOne">What Will The Mint Price Be? </h2>
                                 </div>
                                 <div id="collapsethree" class="collapse" aria-labelledby="headingthree" data-parent="#accordionExample">
                                    <div class="card-body">TBD. Join the discord to chat about it.</div>
                                 </div>
                              </div>
                              <div class="card mt_40">
                                 <div class="card-header" id="headingfive">
                                    <h2 class="mb-0" data-toggle="collapse" data-target="#collapsefive" aria-expanded="true" aria-controls="collapsefive">i&#x27;ve never bought an nFT, how do I do it?</h2>
                                 </div>
                                 <div id="collapsefive" class="collapse" aria-labelledby="headingfive" data-parent="#accordionExample">
                                    <div class="card-body">Download Metamask.io. You&#x27;ll need to transfer Ethereum into Metamask from another wallet (Coinbase for example). Then go on Opensea, connect your Metamask wallet and buy away!</div>
                                 </div>
                              </div>
                              <div class="card mt_40">
                                 <div class="card-header" id="headingsix">
                                    <h2 class="mb-0" data-toggle="collapse" data-target="#collapsesix" aria-expanded="true" aria-controls="collapsesix">Can You Send Me A Free Crunchy Cow?</h2>
                                 </div>
                                 <div id="collapsesix" class="collapse" aria-labelledby="headingsix" data-parent="#accordionExample">
                                    <div class="card-body">Sorry, but that&#x27;s not possible. If you would like a chance to get airdropped a cow, buy 1 and sign up for the mailing list or discord to be notified when we&#x27;ve hit a milestone. </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <footer class="position-relative">
                  <img class="footer-shape position-absolute" src="img/footer-shape.png" alt=""/>
                  <div class="container">
                     <div class="row align-items-end">
                        <div class="col-xl-6 col-lg-7 col-md-6 footer-logo-custom">
                           <div>
                              <a class="footer-logo" href="#"><img src="img/footer-logo.png" alt=""/></a>
                              <div class="footer-content d-flex align-items-center">
                                 <p>All Rights Reserved © 2021 </p>
                              </div>
                           </div>
                        </div>
                        <div class="col-xl-6 col-lg-5 col-md-6 footer-logo-custom">
                           <div class="footer-social text-right"><a href="https://twitter.com/crunchycows"><i class="fab fa-twitter"></i></a></div>
                        </div>
                     </div>
                  </div>
               </footer>
               <div class="modal first-modal fade" id="exampleModal" tabindex="-1" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                     <div class="modal-content">
                        <div class="modal-header-shape">
                           <img class="w-100" src="img/modal-header.png" alt=""/>
                           <h2>COLLECT CRUNCHY COWS</h2>
                           <span class="close" data-dismiss="modal"></span>
                        </div>
                        <div></div>
                        <div class="modal-body">
                           <h2>
                              Per Cow cost= <!-- -->-<!-- -->ETH
                           </h2>
                           <h4 class="hour-text"></h4>
                           <center>
                              <div class="d-flex p-2 align-items-center mt_30 wd50">
                                 <h2 class="mr_10">COWS</h2>
                                 <div><input type="text" class="input-info active" disabled="" placeholder="0"/></div>
                              </div>
                           </center>
                           <div class="text-center mt_30"><button class="connect-btn">Wallet</button><span class="connect-border"></span><button class="connect-btn">MINT</button></div>
                        </div>
                     </div>
                  </div>
               </div>
               <a href="#" class="back-to-top"><i class="fal fa-angle-up"></i></a>
   </body>
   </div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/","query":{},"buildId":"Pr6c9aHeV6D7BUCsyX8zD","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script></body>
</html>